CREATE TABLE CDMH_STAGING.GENDER_XWALK
(
  CDM_NAME character varying(100 ) 
, CDM_TBL character varying(100 ) 
, SRC_GENDER character varying(20 ) 
, FHIR_CD character varying(100 ) 
, TARGET_CONCEPT_ID integer NOT NULL 
, TARGET_CONCEPT_NAME character varying(255 ) NOT NULL 
, TARGET_DOMAIN_ID character varying(20 ) NOT NULL 
, TARGET_VOCABULARY_ID character varying(20 ) NOT NULL 
, TARGET_CONCEPT_CLASS_ID character varying(20 ) NOT NULL 
, TARGET_STANDARD_CONCEPT character varying(1 ) 
, TARGET_CONCEPT_CODE character varying(50 ) NOT NULL 
) 
;
Insert into CDMH_STAGING.GENDER_XWALK (CDM_NAME,CDM_TBL,SRC_GENDER,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','DEMOGRAPHIC','M','male',8507,'MALE','Gender','Gender','Gender','S','M');
Insert into CDMH_STAGING.GENDER_XWALK (CDM_NAME,CDM_TBL,SRC_GENDER,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','DEMOGRAPHIC','F','female',8532,'FEMALE','Gender','Gender','Gender','S','F');
Insert into CDMH_STAGING.GENDER_XWALK (CDM_NAME,CDM_TBL,SRC_GENDER,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','DEMOGRAPHIC','A',null,0,'Ambiguous','Gender','Gender','Gender','S','0');
Insert into CDMH_STAGING.GENDER_XWALK (CDM_NAME,CDM_TBL,SRC_GENDER,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','DEMOGRAPHIC','NI','unknown',0,'No Information','Gender','Gender','Gender','S','0');
Insert into CDMH_STAGING.GENDER_XWALK (CDM_NAME,CDM_TBL,SRC_GENDER,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','DEMOGRAPHIC','OT','other',0,'Other','Gender','Gender','Gender','S','0');
Insert into CDMH_STAGING.GENDER_XWALK (CDM_NAME,CDM_TBL,SRC_GENDER,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','DEMOGRAPHIC','UN','unknown',0,'Unknown','Gender','Gender','Gender','S','0');
Insert into CDMH_STAGING.GENDER_XWALK (CDM_NAME,CDM_TBL,SRC_GENDER,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('I2B2ACT','PATIENT_DIMENSION','DEM|SEX:M','male',8507,'Male','Gender','Gender','Gender','S','M');
Insert into CDMH_STAGING.GENDER_XWALK (CDM_NAME,CDM_TBL,SRC_GENDER,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('I2B2ACT','PATIENT_DIMENSION','DEM|SEX:F','female',8532,'FEMALE','Gender','Gender','Gender','S','F');
Insert into CDMH_STAGING.GENDER_XWALK (CDM_NAME,CDM_TBL,SRC_GENDER,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('I2B2ACT','PATIENT_DIMENSION','DEM|SEX:NI','unknown',0,'No Information','Gender','Gender','Gender','S','0');
Insert into CDMH_STAGING.GENDER_XWALK (CDM_NAME,CDM_TBL,SRC_GENDER,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('I2B2ACT','PATIENT_DIMENSION','DEM|SEX:O','Other',0,'Other','Gender','Gender','Gender','S','0');
Insert into CDMH_STAGING.GENDER_XWALK (CDM_NAME,CDM_TBL,SRC_GENDER,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('I2B2ACT','PATIENT_DIMENSION','DEM|SEX:A',null,0,'Ambiguous','Gender','Gender','Gender','S','0');